'use strict';

Object.defineProperty(exports, "__esModule", {
	value: true
});
var textFeatures = new Array('ping', ':denis:', 'booster', 'Ah mais c\'est mon petit f0ster meister ça!', 'tenaga', 'Ce genre de brousoufeur pimpant mamen. Mashalux le blackbeard', 'neitsa', 'Ah oui tout de même ce genre de joueur sur site mamen.', 'AH!', 'https://giphy.com/gifs/ah-denis-brogniart-3oKIPCMDrutYJBSQ6Y', 'AH !', 'https://giphy.com/gifs/ah-denis-brogniart-3oKIPCMDrutYJBSQ6Y', 'ah', 'https://giphy.com/gifs/ah-denis-brogniart-3oKIPCMDrutYJBSQ6Y', 'ah!', 'https://giphy.com/gifs/ah-denis-brogniart-3oKIPCMDrutYJBSQ6Y', 'AH', 'https://giphy.com/gifs/ah-denis-brogniart-3oKIPCMDrutYJBSQ6Y', 'ah !', 'https://giphy.com/gifs/ah-denis-brogniart-3oKIPCMDrutYJBSQ6Y', 'salope', 'Viens dans le 93 bonhomme je te couches', 'kad', 'http://imgur.com/a/hJ0Y3', 'pardon', 'http://imgur.com/a/JuWOo', 'mamie ?', 'En quoi puis-je t\'aider mon chtio ?', '@Mamie Brigitte', 'En quoi puis-je t\'aider mon chtio ?', 'comment vas ton oignon ?', 'AAh pimp moi tout en\'dans l\'oignon fils.', 'oui ?', 'non.', 'oui', 'ta gueule sodomite', 'non', 'suce sodomite', 'toujours plus', 'toujours moins.', 'chaning', 'Mais quel QUATTABACCK de qualité !', 'chaningT', 'Mais quel QUATTABACCK !', 'qb', 'QUATTABACCK', 'f0ster', 'Oh tu vas mieux épeler le nom de mon petit-fils, sac a foutre. (f0ster)', 'la la land', 'Mon film préféré, comment as-tu deviné ? It\'s another day of sun!', 'nights of fire', 'https://www.youtube.com/watch?v=tNveMjoSxp0', 'deja vu', 'https://www.youtube.com/watch?v=dv13gl0a-FA', 'gas gas gas', 'https://www.youtube.com/watch?v=atuFSv2bLa8', 'takumi!', 'http://imgur.com/a/gIgG6', 'suce un pouce', 'J\'aurai pas aimé xDD, défonce le putain', '!r6', '@everyone, Go jouer à Rainbow Six: Siege !', 'indignité', 'http://imgur.com/a/HSy5X', 'indignite', 'http://imgur.com/a/HSy5X', 'quelle indignité', 'http://imgur.com/a/HSy5X', 'quelle indignite', 'http://imgur.com/a/HSy5X', 'ya', 'https://giphy.com/gifs/l0Iy6dwHVErwWcRK8', 'yaa', 'https://giphy.com/gifs/l0Iy6dwHVErwWcRK8', 'yaaa', 'https://giphy.com/gifs/l0Iy6dwHVErwWcRK8', 'yah', 'https://giphy.com/gifs/l0Iy6dwHVErwWcRK8', 'yaa!', 'https://giphy.com/gifs/l0Iy6dwHVErwWcRK8', 'yaah', 'https://giphy.com/gifs/l0Iy6dwHVErwWcRK8');
// client.on('message', function (message) {
//   if (message.content === 'takumi!') {
//     message.reply('http://imgur.com/a/gIgG6');
//   }
// });
//"Vous êtes actuellement sur le channel #" + message.TextChannel.name  + ". The topic is :" + message.TextChannel.topic + "sur le serveur " + message.TextChannel.Guild.name

exports.default = textFeatures;